### ISSUE TITLE
Remove JB branding bar

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/flyte-docs#3]
Can we maybe just remove the whole gray bar? Unless someone has something they want to put there
![image](https://github.com/flytegg/flyte-docs/assets/138625055/fdb34aac-5514-41a5-8e40-f646520ca45c)

**Comment by joshdevous** [comment]
Yeah fuck that shit off

**Comment by joshdevous** [comment]
Unless they have TOS preventing it 😭

**Comment by Dawsson** [comment]
if we cant remove it, we could just link flyte.gg to the bottom?

**Comment by stephendotgg** [comment]
> if we cant remove it, we could just link flyte.gg to the bottom?

yeah prioritise removing then if not link to our big daddy site. Perhaps the logo at the top left could link there anyway?

**Comment by Dawsson** [comment]
![image](https://github.com/flytegg/flyte-docs/assets/88049488/276bc35d-b31a-427c-a0d0-ec12386c3937)

Thoughts? Feels empty if I just remove that branding completely

![image](https://github.com/flytegg/flyte-docs/assets/88049488/6cd3e31c-0963-477d-baf5-2fa5dddf7315)

**Comment by stephendotgg** [comment]
could maybe move the copyriight sentence to the right side?

**Comment by stephendotgg** [comment]
or the first screenshot works too that looks good

**Comment by Dawsson** [comment]
Are we good to close assuming its fine to keep due to new populated footer?

**Comment by stephendotgg** [comment]
yar
