### ISSUE TITLE
Pink!

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/flyte-docs#5]
The highlight color dotted around the site should be our branded Flyte pink
![image](https://github.com/flytegg/flyte-docs/assets/138625055/16232063-5d60-4ab1-84ed-5b489eda63d4)

**Comment by Dawsson** [comment]
![image](https://github.com/flytegg/flyte-docs/assets/88049488/796ed08d-db3a-496a-981b-dc757daa38b2)

Should we change the coloring scheme at all?

**Comment by Dawsson** [comment]
Ill see if I can make a custom theme easily

**Comment by stephendotgg** [comment]
@joshbker ?

**Comment by Dawsson** [comment]
Wait just to make sure, the blue should be replaced with pink correct? Just want to make sure you're not talking about any icons. Can you link me the Hex code on top of that please, not sure what the official hex is

**Comment by stephendotgg** [comment]
Join the club, one second

**Comment by joshdevous** [comment]
I'll send it

**Comment by joshdevous** [comment]
We should put branding in the docs too

**Comment by stephendotgg** [comment]
agree

**Comment by joshdevous** [comment]
These are the two pinks we use:
```
Pink: #F37BDA
Light Pink: #FEBDC0
```

**Comment by Dawsson** [comment]
Branding as in: https://github.com/flytegg/flyte-docs/issues/2 or what?

**Comment by Dawsson** [comment]
ty

**Comment by joshdevous** [comment]
I think we could just change blue to pink. Maybe also change the code embed theme to GitHub Dark? It's so beautiful compared to default JetBrains

**Comment by Dawsson** [comment]
Closed as deployed using GH Action, will create a new issue for code embed theme.
